name: Send Task Reminders

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  trigger-reminder-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reminder API Endpoint
        run: |
          curl -i -X POST '${{ secrets.PRODUCTION_URL }}/api/cron/reminders' \
          -H 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' \
          -H 'Content-Type: application/json'
